# Generated by Django 5.2.11 on 2026-02-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="user_info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=20, unique=True)),
                ("password", models.CharField(max_length=20)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "user_info",
            },
        ),
    ]
