# Generated by Django 5.2.11 on 2026-02-15 03:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("book_name", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("subject", models.CharField(max_length=255)),
                ("stock", models.IntegerField(default=0)),
                ("reviewers", models.IntegerField(default=0)),
                ("UPC", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField()),
                ("rating", models.IntegerField(default=0)),
                ("image", models.URLField(max_length=500)),
            ],
            options={
                "db_table": "book_info",
            },
        ),
    ]
