# Generated by Django 5.2.11 on 2026-02-15 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("browse_books", models.CharField(max_length=255)),
                ("search_time", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_histories",
                        to="users.user_info",
                    ),
                ),
            ],
            options={
                "db_table": "search_history",
                "ordering": ["-search_time"],
            },
        ),
    ]
