# Generated by Django 5.2.11 on 2026-02-15 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_profile", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchhistory",
            name="username",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
