# Generated by Django 5.2.11 on 2026-02-22 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_profile", "0002_searchhistory_username"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("book_upc", models.CharField(max_length=50, verbose_name="书名编号")),
                ("book_name", models.CharField(max_length=50, verbose_name="书名")),
                (
                    "collect_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="收藏时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="username_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.user_info",
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "db_table": "book_collection",
                "ordering": ["-collect_time"],
            },
        ),
    ]
